server_port: 80
max_url_length: 300
shortening_size: 10

database:
  db_host: "localhost"
  db_name: "urlshortener"
  db_user: "timickb"
  db_password: ""
  db_port: 5432


# if empty, all origins are allowed
origins:
  - http://localhost:9000