version: '3.9'

services:
  db:
    image: postgres:14.3-alpine
    command: postgres -c 'max_connections=1000'
    restart: on-failure
    volumes:
      - ./.postgres_data/:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust

  migrate:
    image: migrate/migrate
    entrypoint: "migrate -path /tmp/migrations -database postgresql://${DB_USER}@db/${DB_NAME}?sslmode=${SSL_MODE}"
    command: up
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  api:
    image: timickb/url_shortener_api:latest
    build: ./
    container_name: api
    restart: on-failure
    command: /app -config-source=env
    ports:
      - "9000:8080"
    depends_on:
      - db
      - migrate
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    tty: true
